zuul:
  prefix: /api
  strip-prefix: true
  routes:
    user-service:
      path: /user/**
      strip-prefix: false
      service-id: springcloud-user
    order-service:
      path: /order/**
      strip-prefix: false
      service-id: springcloud-order